steps:
  # Build image
  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "gcr.io/$PROJECT_ID/core", "."]

  # Deploy image

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "gcr.io/$PROJECT_ID/core"]

tags: ["runner"]
# Image already pushed - Reference this runner image with the following URL = gcr.io/$PROJECT_ID/core  $PROJECT_ID=coffee-and-feel

# RUN gcloud builds submit DOCKERFILE_SOURCE_PATH --config CLOUDBUILD_YAML_SOURCE_PATH (this yaml file) --project GCLOUD_PROJECT_ID
# once its uploded you can reference this as the base of any other images
